### ISSUE TITLE
Upgrade path for new versions

### ISSUE THREAD

**Issue by kdoroszewicz** [DoneDeal0/alright-react-app#1]
Is there an upgrade plan for alright-react-app? As far as I can see I'am stuck with the settings and optimizations done up to the moment I create the project with it, there's currently no mechanism to keep up to date besides doing manual work of diffing the configs and package.json between versions. Are there plans to address this or is it not a concern of the project?

**Comment by DoneDeal0** [comment]
Hi,

I'll regularly update the dependencies. As soon as a new ARA version is available, your terminal will download it for you and create a new project with up-to-date libs. 

However, feel free to bump the dependencies anytime on your current project. A good way to do it with `yarn` is to enter `yarn upgrade-interactive --latest` in your terminal so you can simply check which libs have newer versions and select them by pressing the space bar. 

CRA works the same way.

**Comment by kdoroszewicz** [comment]
Yes, it's good that you're keeping the deps up to date but it's not just dependencies isn't it? The config files for testing, build won't update themselves, updating dependencies of already created project also is up the user of the template.

CRA definitely doesn't work the same way because practically all of build config and associated packages are kept hidden in `react-scripts` package and thus you need to update only `react-scripts` to get the benefits of the upgrade without the hassle of manually updating configs, plugins, packages etc. Other starters I used like `tsdx` or `dts-cli` also hide the optimized config inside the package.

I'm just wondering if you have some strategy in mind to help the upgrade proces when you change the build config or upgrade the package in this template. Currently none of the people that used your project will get the improvements you make to this starter in the future.

**Comment by DoneDeal0** [comment]
This is correct. I expose the config by design. I don't want to lock people with a hidden/magic package. There are many advantages to that (for example, you don't have to wait for me to update a lib or to optimize anything, the project is highly scalable), but it's definitely less easy/accessible. There are always pro and cons^^.
