### ISSUE TITLE
.swcrc missing baseUrl in its config

### ISSUE THREAD

**Issue by bustertown** [DoneDeal0/alright-react-app#4]
After `npx alright-react-app` and trying to run `yarn | npm run dev`, an error is thrown showing that the project is missing `jsc.baseUrl` as it needs to be an absolute path. Specifying the baseUrl in the `.swcrc` fixes the issue. i.e. 
```
{
  "jsc": {
    "baseUrl": "./src",
    // all the other fun config
}

**Comment by DoneDeal0** [comment]
Hi @bustertown, thanks for pointing this out. I'm really sorry I didn't fix this sooner. I've updated and double-checked all the dependencies. Sorry again.

**Comment by bustertown** [comment]
No worries, I should made a pull request to make your life a bit easier. Nice little project though!
